/*
 * Customer BFF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AddDamageFixationsRequest : IEquatable<AddDamageFixationsRequest>
    {
        /// <summary>
        /// Gets or Sets Fixations
        /// </summary>
        [Required]
        [DataMember(Name="fixations", EmitDefaultValue=false)]
        public List<Fixation> Fixations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddDamageFixationsRequest {\n");
            sb.Append("  Fixations: ").Append(Fixations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AddDamageFixationsRequest)obj);
        }

        /// <summary>
        /// Returns true if AddDamageFixationsRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AddDamageFixationsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddDamageFixationsRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Fixations == other.Fixations ||
                    Fixations != null &&
                    other.Fixations != null &&
                    Fixations.SequenceEqual(other.Fixations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Fixations != null)
                    hashCode = hashCode * 59 + Fixations.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AddDamageFixationsRequest left, AddDamageFixationsRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AddDamageFixationsRequest left, AddDamageFixationsRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
