/*
 * Customer BFF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BookVehicleRequest : IEquatable<BookVehicleRequest>
    {
        /// <summary>
        /// Gets or Sets VehicleId
        /// </summary>
        [Required]
        [DataMember(Name="vehicleId", EmitDefaultValue=true)]
        public Guid VehicleId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [Required]
        [DataMember(Name="customerId", EmitDefaultValue=true)]
        public Guid CustomerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BookVehicleRequest {\n");
            sb.Append("  VehicleId: ").Append(VehicleId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BookVehicleRequest)obj);
        }

        /// <summary>
        /// Returns true if BookVehicleRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of BookVehicleRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BookVehicleRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    VehicleId == other.VehicleId ||
                    
                    VehicleId.Equals(other.VehicleId)
                ) && 
                (
                    CustomerId == other.CustomerId ||
                    
                    CustomerId.Equals(other.CustomerId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + VehicleId.GetHashCode();
                    
                    hashCode = hashCode * 59 + CustomerId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BookVehicleRequest left, BookVehicleRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BookVehicleRequest left, BookVehicleRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
