/*
 * Customer BFF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{ 
        /// <summary>
        /// Gets or Sets DrivingLicenseStatus
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<DrivingLicenseStatus>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DrivingLicenseStatus
        {
            
            /// <summary>
            /// Enum ApprovedEnum for approved
            /// </summary>
            [EnumMember(Value = "approved")]
            ApprovedEnum = 1,
            
            /// <summary>
            /// Enum PendingPhotosAddingEnum for pendingPhotosAdding
            /// </summary>
            [EnumMember(Value = "pendingPhotosAdding")]
            PendingPhotosAddingEnum = 2,
            
            /// <summary>
            /// Enum PendingProcessingEnum for pendingProcessing
            /// </summary>
            [EnumMember(Value = "pendingProcessing")]
            PendingProcessingEnum = 3,
            
            /// <summary>
            /// Enum RejectedEnum for rejected
            /// </summary>
            [EnumMember(Value = "rejected")]
            RejectedEnum = 4,
            
            /// <summary>
            /// Enum ExpiredEnum for expired
            /// </summary>
            [EnumMember(Value = "expired")]
            ExpiredEnum = 5
        }
}
