/*
 * Customer BFF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{ 
        /// <summary>
        /// Gets or Sets FixationCategory
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<FixationCategory>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum FixationCategory
        {
            
            /// <summary>
            /// Enum MinorDamageEnum for minorDamage
            /// </summary>
            [EnumMember(Value = "minorDamage")]
            MinorDamageEnum = 1,
            
            /// <summary>
            /// Enum SignificantDamageEnum for significantDamage
            /// </summary>
            [EnumMember(Value = "significantDamage")]
            SignificantDamageEnum = 2
        }
}
