/*
 * Customer BFF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetVehicleByIdResponse : IEquatable<GetVehicleByIdResponse>
    {
        /// <summary>
        /// Gets or Sets VehicleId
        /// </summary>
        [DataMember(Name="vehicleId", EmitDefaultValue=false)]
        public string VehicleId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=true)]
        public Status Status { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>
        [DataMember(Name="brand", EmitDefaultValue=false)]
        public string Brand { get; set; }

        /// <summary>
        /// Gets or Sets CarModelId
        /// </summary>
        [DataMember(Name="carModelId", EmitDefaultValue=false)]
        public string CarModelId { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [DataMember(Name="color", EmitDefaultValue=true)]
        public Color Color { get; set; }

        /// <summary>
        /// Gets or Sets PlateNumber
        /// </summary>
        [DataMember(Name="plate_number", EmitDefaultValue=false)]
        public string PlateNumber { get; set; }

        /// <summary>
        /// Gets or Sets FuelLevelPercents
        /// </summary>
        [DataMember(Name="fuelLevelPercents", EmitDefaultValue=true)]
        public int FuelLevelPercents { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="location", EmitDefaultValue=false)]
        public Location Location { get; set; }

        /// <summary>
        /// Gets or Sets PricePerMinute
        /// </summary>
        [DataMember(Name="pricePerMinute", EmitDefaultValue=true)]
        public decimal PricePerMinute { get; set; }

        /// <summary>
        /// Gets or Sets PricePerHour
        /// </summary>
        [DataMember(Name="pricePerHour", EmitDefaultValue=true)]
        public decimal PricePerHour { get; set; }

        /// <summary>
        /// Gets or Sets PricePerDay
        /// </summary>
        [DataMember(Name="pricePerDay", EmitDefaultValue=true)]
        public decimal PricePerDay { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetVehicleByIdResponse {\n");
            sb.Append("  VehicleId: ").Append(VehicleId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  CarModelId: ").Append(CarModelId).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  PlateNumber: ").Append(PlateNumber).Append("\n");
            sb.Append("  FuelLevelPercents: ").Append(FuelLevelPercents).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  PricePerMinute: ").Append(PricePerMinute).Append("\n");
            sb.Append("  PricePerHour: ").Append(PricePerHour).Append("\n");
            sb.Append("  PricePerDay: ").Append(PricePerDay).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetVehicleByIdResponse)obj);
        }

        /// <summary>
        /// Returns true if GetVehicleByIdResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GetVehicleByIdResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetVehicleByIdResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    VehicleId == other.VehicleId ||
                    VehicleId != null &&
                    VehicleId.Equals(other.VehicleId)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                ) && 
                (
                    Brand == other.Brand ||
                    Brand != null &&
                    Brand.Equals(other.Brand)
                ) && 
                (
                    CarModelId == other.CarModelId ||
                    CarModelId != null &&
                    CarModelId.Equals(other.CarModelId)
                ) && 
                (
                    Color == other.Color ||
                    
                    Color.Equals(other.Color)
                ) && 
                (
                    PlateNumber == other.PlateNumber ||
                    PlateNumber != null &&
                    PlateNumber.Equals(other.PlateNumber)
                ) && 
                (
                    FuelLevelPercents == other.FuelLevelPercents ||
                    
                    FuelLevelPercents.Equals(other.FuelLevelPercents)
                ) && 
                (
                    Location == other.Location ||
                    Location != null &&
                    Location.Equals(other.Location)
                ) && 
                (
                    PricePerMinute == other.PricePerMinute ||
                    
                    PricePerMinute.Equals(other.PricePerMinute)
                ) && 
                (
                    PricePerHour == other.PricePerHour ||
                    
                    PricePerHour.Equals(other.PricePerHour)
                ) && 
                (
                    PricePerDay == other.PricePerDay ||
                    
                    PricePerDay.Equals(other.PricePerDay)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (VehicleId != null)
                    hashCode = hashCode * 59 + VehicleId.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (Brand != null)
                    hashCode = hashCode * 59 + Brand.GetHashCode();
                    if (CarModelId != null)
                    hashCode = hashCode * 59 + CarModelId.GetHashCode();
                    
                    hashCode = hashCode * 59 + Color.GetHashCode();
                    if (PlateNumber != null)
                    hashCode = hashCode * 59 + PlateNumber.GetHashCode();
                    
                    hashCode = hashCode * 59 + FuelLevelPercents.GetHashCode();
                    if (Location != null)
                    hashCode = hashCode * 59 + Location.GetHashCode();
                    
                    hashCode = hashCode * 59 + PricePerMinute.GetHashCode();
                    
                    hashCode = hashCode * 59 + PricePerHour.GetHashCode();
                    
                    hashCode = hashCode * 59 + PricePerDay.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GetVehicleByIdResponse left, GetVehicleByIdResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetVehicleByIdResponse left, GetVehicleByIdResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
