/*
 * Customer BFF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UpdateModelTariffRequest : IEquatable<UpdateModelTariffRequest>
    {
        /// <summary>
        /// Gets or Sets PricePerMinute
        /// </summary>
        [Required]
        [DataMember(Name="pricePerMinute", EmitDefaultValue=true)]
        public decimal PricePerMinute { get; set; }

        /// <summary>
        /// Gets or Sets PricePerHour
        /// </summary>
        [Required]
        [DataMember(Name="pricePerHour", EmitDefaultValue=true)]
        public decimal PricePerHour { get; set; }

        /// <summary>
        /// Gets or Sets PricePerDay
        /// </summary>
        [Required]
        [DataMember(Name="price_per_day", EmitDefaultValue=true)]
        public decimal PricePerDay { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateModelTariffRequest {\n");
            sb.Append("  PricePerMinute: ").Append(PricePerMinute).Append("\n");
            sb.Append("  PricePerHour: ").Append(PricePerHour).Append("\n");
            sb.Append("  PricePerDay: ").Append(PricePerDay).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdateModelTariffRequest)obj);
        }

        /// <summary>
        /// Returns true if UpdateModelTariffRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateModelTariffRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateModelTariffRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PricePerMinute == other.PricePerMinute ||
                    
                    PricePerMinute.Equals(other.PricePerMinute)
                ) && 
                (
                    PricePerHour == other.PricePerHour ||
                    
                    PricePerHour.Equals(other.PricePerHour)
                ) && 
                (
                    PricePerDay == other.PricePerDay ||
                    
                    PricePerDay.Equals(other.PricePerDay)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + PricePerMinute.GetHashCode();
                    
                    hashCode = hashCode * 59 + PricePerHour.GetHashCode();
                    
                    hashCode = hashCode * 59 + PricePerDay.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UpdateModelTariffRequest left, UpdateModelTariffRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdateModelTariffRequest left, UpdateModelTariffRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
