/*
 * Customer BFF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UploadPhotosRequest : IEquatable<UploadPhotosRequest>
    {
        /// <summary>
        /// Gets or Sets FrontPhotoBytes
        /// </summary>
        [Required]
        [DataMember(Name="frontPhotoBytes", EmitDefaultValue=false)]
        public byte[] FrontPhotoBytes { get; set; }

        /// <summary>
        /// Gets or Sets BackPhotoBytes
        /// </summary>
        [Required]
        [DataMember(Name="backPhotoBytes", EmitDefaultValue=false)]
        public byte[] BackPhotoBytes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UploadPhotosRequest {\n");
            sb.Append("  FrontPhotoBytes: ").Append(FrontPhotoBytes).Append("\n");
            sb.Append("  BackPhotoBytes: ").Append(BackPhotoBytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UploadPhotosRequest)obj);
        }

        /// <summary>
        /// Returns true if UploadPhotosRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of UploadPhotosRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UploadPhotosRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FrontPhotoBytes == other.FrontPhotoBytes ||
                    FrontPhotoBytes != null &&
                    FrontPhotoBytes.Equals(other.FrontPhotoBytes)
                ) && 
                (
                    BackPhotoBytes == other.BackPhotoBytes ||
                    BackPhotoBytes != null &&
                    BackPhotoBytes.Equals(other.BackPhotoBytes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FrontPhotoBytes != null)
                    hashCode = hashCode * 59 + FrontPhotoBytes.GetHashCode();
                    if (BackPhotoBytes != null)
                    hashCode = hashCode * 59 + BackPhotoBytes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UploadPhotosRequest left, UploadPhotosRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UploadPhotosRequest left, UploadPhotosRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
