/*
 * Customer BFF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using OpenApiContractV1.Attributes;
using OpenApiContractV1.Models;

namespace OpenApiContractV1.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class BookingApiController : ControllerBase
    { 
        /// <summary>
        /// Book a vehicle
        /// </summary>
        /// <param name="bookVehicleRequest"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="500">Internal server error</response>
        [HttpPost]
        [Route("/booking/book-vehicle")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("BookVehicle")]
        [SwaggerResponse(statusCode: 200, type: typeof(BookVehicleResponse), description: "Successful operation")]
        public abstract Task<IActionResult> BookVehicle([FromBody]BookVehicleRequest bookVehicleRequest);

        /// <summary>
        /// Cancel a booking
        /// </summary>
        /// <param name="bookingId">Идентификатор бронирования</param>
        /// <response code="200">Successful operation</response>
        /// <response code="500">Internal server error</response>
        [HttpPost]
        [Route("/booking/{bookingId}/cancel")]
        [ValidateModelState]
        [SwaggerOperation("CancelBookingVehicle")]
        public abstract Task<IActionResult> CancelBookingVehicle([FromRoute (Name = "bookingId")][Required]Guid bookingId);
    }
}
